name: Daily Script

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Replace with the Python version you need
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twilio==9.2.1 requests==2.32.3
        
    - name: Run script
      env:
        # Set your environment variables here
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        LAT: ${{ secrets.LAT }}
        LON: ${{ secrets.LON }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        TWILIO_TO: ${{ secrets.TWILIO_TO }}
      run: python 35-weather-bot/weather_api.py
